module GamePalitos{
	interface GamePalitosServer {
  	  void registraCliente(in string nomeCliente);
      void mensagemBroadCast(in string mensagem, in boolean quebraDelinha);
			void mensagemBroadCastNoJogo(in string mensagem, in boolean quebraDelinha);
      void pedePalitos();
      void pedePalpite(in string nomeCliente);
		  void recebePalpite(in string nomeCliente, in long palitos);
		  void verificaPalpites();
      void somaPalitos(in long palitos);
		  void alteraTurno();
		  void reiniciaValores();
			void retiraUmPalito(in string nomeCliente);
			void verificaVenceu(in string nomeCliente);
			long buscaQuantidadePalitos(in string nomeCliente);
			boolean verificaEstaNoJogo(in string nomeCliente);
			boolean palpiteValido(in long palpite);
	};

	typedef sequence<string> names;
	interface GamePalitosCliente {
      void novaMensagem(in string mensagem);
			void novaMensagemSemQuebra(in string mensagem);
      void escolhePalitos();
      void escolhePalpite();
			void removePalito();
			long getPalitos();
	};
};
