module GamePalitos{
	interface GamePalitosServer {
  	  void registraCliente(in string nomeCliente);
      void mensagemBroadCast(in string mensagem);
      void pedePalitos();
      void pedePalpite(in string nomeCliente);
	  void recebePalpite(in string nomeCliente, in long palitos);
	  void verificaPalpites();
      void somaPalitos(in long palitos);
	  void alteraTurno();
	  void reiniciaValores();
	};

	typedef sequence<string> names;
	interface GamePalitosCliente {
      void novaMensagem(in string mensagem);
      void escolhePalitos();
      void escolhePalpite();
	};
};
