module GamePalitos{
	interface GamePalitosServer {
  	  void registraCliente(in string nomeCliente);
      void mensagemBroadCast(in string mensagem);
      void pedePalitos();
      void pedePalpite();
	  void verificaPalpites();
      void somaPalitos(in long palitos);
	};

	typedef sequence<string> names;
	interface GamePalitosCliente {
      void novaMensagem(in string mensagem);
      void escolhePalitos();
      void escolhePalpite();
	};
};
