package GamePalitos;


/**
* GamePalitos/GamePalitosCliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Terça-feira, 27 de Junho de 2017 00h54min36s BRT
*/

public interface GamePalitosCliente extends GamePalitosClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GamePalitosCliente
