package GamePalitos;


/**
* GamePalitos/GamePalitosCliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Quarta-feira, 28 de Junho de 2017 02h45min35s BRT
*/

public interface GamePalitosCliente extends GamePalitosClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GamePalitosCliente
