package GamePalitos;


/**
* GamePalitos/GamePalitosClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Terça-feira, 27 de Junho de 2017 00h54min36s BRT
*/

public interface GamePalitosClienteOperations 
{
  void novaMensagem (String mensagem);
  void escolhePalitos ();
  void escolhePalpite ();
} // interface GamePalitosClienteOperations
