package GamePalitos;


/**
* GamePalitos/GamePalitosClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Quarta-feira, 28 de Junho de 2017 01h59min42s BRT
*/

public interface GamePalitosClienteOperations 
{
  void novaMensagem (String mensagem);
  void escolhePalitos ();
  void escolhePalpite ();
  void removePalito ();
  int getPalitos ();
} // interface GamePalitosClienteOperations
