package GamePalitos;


/**
* GamePalitos/GamePalitosServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Quarta-feira, 28 de Junho de 2017 01h59min42s BRT
*/

public interface GamePalitosServer extends GamePalitosServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GamePalitosServer
