package GamePalitos;


/**
* GamePalitos/GamePalitosServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Terça-feira, 27 de Junho de 2017 09h17min28s BRT
*/

public interface GamePalitosServer extends GamePalitosServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GamePalitosServer
