package GamePalitos;


/**
* GamePalitos/GamePalitosServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Game.idl
* Terça-feira, 27 de Junho de 2017 09h17min28s BRT
*/

public interface GamePalitosServerOperations 
{
  void registraCliente (String nomeCliente);
  void mensagemBroadCast (String mensagem);
  void pedePalitos ();
  void pedePalpite ();
  void verificaPalpites ();
  void somaPalitos (int palitos);
} // interface GamePalitosServerOperations
